# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de780e8825240871e49c045eefa5d6bbe09dc9a4a62ca7d969e5e69aa96ad17c45621c082ac757b401012c32aa56b579142da07249be0833b756076ebe583573

test:
  secret_key_base: 77bfe2e96dfaf540640ae23c1f8becc10bfd771c210e13838bc72440a5baacc6e9859ba71e56eb286f8af0aabc5854f8ce4e86cf1105b41bacbef9cdfddb622e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
